sudo: false

language: java
jdk: oraclejdk8

skip_cleanup:true

deploy:
  provider: releases
  api_key:
    secure: IzKN7T88akJTGrM0jioGOZOLA5VuSpKa5a60SIrAZjjvIS79vphdSfFqMiaXJBkpoc5fM8f1wvL/LVVVl0TMcOwe7e0YQiyfAlwYZUu3LsDFl7wfa2AskF4y0ZxKBm/D0aTB+nE9mQO+0xDPqu2dpNFjkN4RbPUZeFD+RKNtVzso/W/KrN8oF7cm/pEX8sKPZHR7cNboyTwbo2NcyByf+Z69x4oW2l0Z/LxCUNnMkFR6G1FtL26lLiqKKaA9sz92JyyDQLoaz7yJ/bmGnOIuwBdcMmmeLdjYAfAFGXjGwYvLyAgi6HhKFWXBgtkOmcar4xKlilWcASr4nEVfOJQvGikWx0yt4yCDisVFaRMB+SIYuerjWkeDX4FzgFhHHFFJS+O3p3j4QYpClf8BKyEJCpeOieIjbO0d8SFh+ojN/OZSEwtUL0LUwJXdLK7+9cJWYx0iuVoQgVoTVhCIa+VkkfDV43g0dXza02dejiVxyZ9mlgg3bskQJYqxVGCEX7rAbwIV8lYsCn5tpyB2LJyzGAEGbRpmX/CyOH8jRXo6p3ByEqGR5MJuSufyez0AN7IQ10wmaneHJYcPlsqna43zuF7LxSP6A7taK7M/RMURlM8Nf13bWddoEkI7PKgBNkGnDs7h1WFL0DBtANs6u1Dnqnpu6Le2sUS48+iJYFBf4O0=
  file: build/libs/JUnitDiff2-1.0.0.jar
  on:
    tags: true
    repo: duckAsteroid/JUnitDiff2
    branch: master
